name: CI

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  chart-package:
    name: Chart package
    uses: hajle-silesia/.github/.github/workflows/shared-chart-package.yaml@v2.2.1
    with:
      docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
      docker-hub-namespace: ${{ vars.DOCKER_HUB_NAMESPACE }}
      dir: charts/file-content-processor
    secrets:
      docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
